"""ones1

Revision ID: 1805244421c3
Revises: 51055282b36c
Create Date: 2019-04-25 11:57:38.359704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1805244421c3'
down_revision = '51055282b36c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'c')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('c', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
