"""threes

Revision ID: 46c698aa4099
Revises: abe3703ea103
Create Date: 2019-04-25 12:22:19.814963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c698aa4099'
down_revision = 'abe3703ea103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'c')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('c', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
