"""one

Revision ID: f701f2488055
Revises: 3518dd545783
Create Date: 2019-04-25 09:04:53.543390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f701f2488055'
down_revision = '3518dd545783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch_categories', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_categories', sa.Column('size', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
